apiVersion: batch/v1
kind: Job
metadata:
  name: vault-main-initializer
  namespace: vault
spec:
  template:
    spec:
      containers:
      - args: []
        env:
        - name: VAULT_ADDR
          value: https://vault.test.wirywolf.com
        - name: VAULT_CACERT
          value: /vault-tls-web/tls.crt
        image: ameypar/k8s-vault-initializer:latest
        imagePullPolicy: IfNotPresent
        name: initializer
        volumeMounts:
        - mountPath: /vault-tls-web
          name: vault-tls-web
      restartPolicy: Never
      serviceAccountName: vault-init
      volumes:
      - name: vault-tls-web
        secret:
          secretName: wildcard-tls-secret
