---
{
   "apiVersion": "v1",
   "kind": "ServiceAccount",
   "metadata": {
      "annotations": { },
      "name": "vault-init",
      "namespace": "vault"
   }
}
---
{
   "apiVersion": "rbac.authorization.k8s.io/v1",
   "kind": "Role",
   "metadata": {
      "annotations": { },
      "name": "vault-init",
      "namespace": "vault"
   },
   "rules": [
      {
         "apiGroups": [
            ""
         ],
         "resources": [
            "secrets"
         ],
         "verbs": [
            "*"
         ]
      }
   ]
}
---
{
   "apiVersion": "rbac.authorization.k8s.io/v1",
   "kind": "RoleBinding",
   "metadata": {
      "annotations": { },
      "name": "vault-init",
      "namespace": "vault"
   },
   "roleRef": {
      "apiGroup": "rbac.authorization.k8s.io",
      "kind": "Role",
      "name": "vault-init"
   },
   "subjects": [
      {
         "kind": "ServiceAccount",
         "name": "vault-init"
      }
   ]
}
---
{
   "apiVersion": "batch/v1",
   "kind": "Job",
   "metadata": {
      "name": "vault-main-initializer",
      "namespace": "vault"
   },
   "spec": {
      "template": {
         "spec": {
            "containers": [
               {
                  "args": [ ],
                  "env": [
                     {
                        "name": "VAULT_ADDR",
                        "value": "https://vault.vault.svc:8200"
                     },
                     {
                        "name": "VAULT_CACERT",
                        "value": "/vault-tls-web/tls.crt"
                     }
                  ],
                  "image": "ameypar/k8s-vault-initializer:latest",
                  "imagePullPolicy": "IfNotPresent",
                  "name": "initializer",
                  "volumeMounts": [
                     {
                        "mountPath": "/vault-tls-web",
                        "name": "vault-tls-web"
                     }
                  ]
               }
            ],
            "restartPolicy": "Never",
            "serviceAccountName": "vault-init",
            "volumes": [
               {
                  "name": "vault-tls-web",
                  "secret": {
                     "secretName": "vault-internal-tls-secret"
                  }
               }
            ]
         }
      }
   }
}
---
{
   "apiVersion": "batch/v1",
   "kind": "Job",
   "metadata": {
      "name": "vault-unsealer-initializer",
      "namespace": "vault"
   },
   "spec": {
      "template": {
         "spec": {
            "containers": [
               {
                  "args": [
                     "-vault-for-autounseal"
                  ],
                  "env": [
                     {
                        "name": "VAULT_ADDR",
                        "value": "https://vault-unsealer.wirywolf.com"
                     },
                     {
                        "name": "VAULT_CACERT",
                        "value": "/vault-tls-web/tls.crt"
                     }
                  ],
                  "image": "ameypar/k8s-vault-initializer:latest",
                  "imagePullPolicy": "IfNotPresent",
                  "name": "initializer",
                  "volumeMounts": [
                     {
                        "mountPath": "/vault-tls-web",
                        "name": "vault-tls-web"
                     }
                  ]
               }
            ],
            "restartPolicy": "Never",
            "serviceAccountName": "vault-init",
            "volumes": [
               {
                  "name": "vault-tls-web",
                  "secret": {
                     "secretName": "wildcard-tls-secret"
                  }
               }
            ]
         }
      }
   }
}
...
