apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      version: 0.13.7
  dependsOn:
  - name: prometheus-stack
  install:
    createNamespace: true
  interval: 30m
  releaseName: metallb
  targetNamespace: metallb-system
  values: |
    prometheus:
      serviceAccount: "prometheus-stack-kube-prom-prometheus"
      namespace: monitoring
      podMonitor:
        enabled: true
        additionalLabels:
          release: prometheus-stack
      prometheusRule:
        enabled: true
        additionalLabels:
          release: prometheus-stack
