apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      version: 1.10.1
  dependsOn:
  - name: prometheus-stack
  - name: longhorn
  - name: kubernetes-reflector
  install:
    createNamespace: true
  interval: 30m
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: "true"
