apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  chart:
    spec:
      chart: longhorn
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: 1.3.2
  install:
    createNamespace: true
  interval: 30m
  releaseName: longhorn
  targetNamespace: longhorn-system
  values:
    values: |-
      "defaultSettings":
        "backupTarget": "s3://amey-backups-longhorn@us-west-004/"
        "backupTargetCredentialSecret": "longhorn-backup-secret"
        "defaultReplicaCount": 1
        "nodeDownPodDeletionPolicy": "delete-both-statefulset-and-deployment-pod"
      "effect": "NoSchedule"
      "longhornDriver":
        "effect": "NoSchedule"
        "tolerations":
        - "key": "node-role.kubernetes.io/master"
          "operator": "Equal"
          "value": "true"
      "longhornManager":
        "effect": "NoSchedule"
        "tolerations":
        - "key": "node-role.kubernetes.io/master"
          "operator": "Equal"
          "value": "true"
      "longhornUI":
        "tolerations":
        - "key": "node-role.kubernetes.io/master"
          "operator": "Equal"
        "value": "true"
      "persistence":
        "defaultClass": false
        "defaultClassReplicaCount": 1
        "reclaimPolicy": "Delete"
