apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: traefik
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 20.8.0
  dependsOn:
  - name: metallb
  install:
    createNamespace: true
  interval: 30m
  targetNamespace: traefik
  values: |
    service:
      ipFamilyPolicy: PreferDualStack
      spec:
        loadBalancerIP: 192.168.1.210
    rbac:
      enabled: true
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
    podAnnotations:
      prometheus.io/port: 8082
      prometheus.io/scrape: true
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: system-cluster-critical
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
