apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-reflector
  namespace: flux-system
spec:
  chart:
    spec:
      chart: reflector
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: kubernetes-reflector
        namespace: flux-system
      version: 6.1.47
  install:
    createNamespace: true
  interval: 30m
  releaseName: kubernetes-reflector
  targetNamespace: cert-manager
