apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      version: 43.1.0
  install:
    createNamespace: true
  interval: 30m
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  values:
    alertmanager:
      alertmanagerSpec:
        configSecret: ""
        podMetadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-inject-secret-slack-webhook-url: tokens/data/slack
            vault.hashicorp.com/agent-inject-template-slack-webhook-url: |
              {{- with secret "tokens/data/slack" -}}
              {{- .Data.data.alarm_webhook_url -}}
              {{- end -}}
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/role: alert-manager
            vault.hashicorp.com/service: vault.test.wirywolf.com
          labels:
            vault-injector: enabled
        storage:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 2Gi
              storageClassName: longhorn
        useExistingSecret: true
    defaultRules:
      rules:
        etcd: false
    kubeApiServer:
      enabled: false
    kubeControllerManager:
      enabled: true
      endpoints:
      - 192.168.1.201
      service:
        enabled: true
        port: 10257
        targetPort: 10257
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: true
      endpoints:
      - 192.168.1.201
    kubeScheduler:
      enabled: true
      endpoints:
      - 192.168.1.201
      service:
        enabled: true
        port: 10259
        targetPort: 10259
    prometheus:
      prometheusSpec:
        storage:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 2Gi
              storageClassName: longhorn
      thanosRulerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 2Gi
              storageClassName: longhorn
    prometheusOperator:
      prometheusConfigReloader:
        resources:
          requests:
            cpu: 100m
      resources:
        requests:
          cpu: 100m
