---
{
   "apiVersion": "source.toolkit.fluxcd.io/v1beta2",
   "kind": "HelmRepository",
   "metadata": {
      "name": "hashicorp",
      "namespace": "flux-system"
   },
   "spec": {
      "interval": "24h",
      "url": "https://helm.releases.hashicorp.com"
   }
}
---
{
   "apiVersion": "helm.toolkit.fluxcd.io/v2beta1",
   "kind": "HelmRelease",
   "metadata": {
      "name": "vault-unsealer",
      "namespace": "flux-system"
   },
   "spec": {
      "chart": {
         "spec": {
            "chart": "vault",
            "interval": "12h",
            "sourceRef": {
               "kind": "HelmRepository",
               "name": "hashicorp",
               "namespace": "flux-system"
            },
            "version": "0.21.0"
         }
      },
      "install": {
         "createNamespace": true
      },
      "interval": "30m",
      "releaseName": "vault-unsealer",
      "targetNamespace": "vault",
      "values": {
         "global": {
            "tlsDisable": false
         },
         "injector": {
            "enabled": true,
            "webhook": {
               "objectSelector": {
                  "matchLabels": {
                     "unseal-injector": "enabled"
                  }
               }
            }
         },
         "server": {
            "auditStorage": {
               "enabled": true,
               "size": "1Gi",
               "storageClass": "longhorn"
            },
            "dataStorage": {
               "size": "1Gi",
               "storageClass": "longhorn"
            },
            "extraEnvironmentVars": {
               "VAULT_CACERT": "/vault-tls-web/tls.crt"
            },
            "standalone": {
               "config": "ui = true\nlistener \"tcp\" {\n  tls_disable = 0\n  tls_cert_file = \"/vault-tls-web/tls.crt\"\n  tls_key_file = \"/vault-tls-web/tls.key\"\n  address = \"[::]:8200\"\n  cluster_address = \"[::]:8201\"\n}\nstorage \"file\" {\n  path = \"/vault/data\"\n}\n",
               "enabled": true
            },
            "volumeMounts": [
               {
                  "mountPath": "/vault-tls-web",
                  "name": "vault-tls-web"
               }
            ],
            "volumes": [
               {
                  "name": "vault-tls-web",
                  "secret": {
                     "secretName": "wildcard-tls-secret"
                  }
               }
            ]
         },
         "ui": {
            "enabled": true,
            "externalPort": 443,
            "loadBalancerIP": "192.168.80.2",
            "serviceType": "LoadBalancer",
            "targetPort": 8200
         }
      }
   }
}
---
{
   "apiVersion": "helm.toolkit.fluxcd.io/v2beta1",
   "kind": "HelmRelease",
   "metadata": {
      "name": "vault",
      "namespace": "flux-system"
   },
   "spec": {
      "chart": {
         "spec": {
            "chart": "vault",
            "interval": "12h",
            "sourceRef": {
               "kind": "HelmRepository",
               "name": "hashicorp",
               "namespace": "flux-system"
            },
            "version": "0.21.0"
         }
      },
      "dependsOn": [
         {
            "name": "vault-unsealer"
         }
      ],
      "install": {
         "createNamespace": true
      },
      "interval": "30m",
      "releaseName": "vault",
      "targetNamespace": "vault",
      "values": {
         "global": {
            "tlsDisable": false
         },
         "injector": {
            "enabled": true,
            "webhook": {
               "objectSelector": {
                  "matchLabels": {
                     "vault-injector": "enabled"
                  }
               }
            }
         },
         "server": {
            "affinity": {
               "podAntiAffinity": {
                  "preferredDuringSchedulingIgnoredDuringExecution": [
                     {
                        "podAffinityTerm": {
                           "labelSelector": {
                              "matchLabels": {
                                 "app.kubernetes.io/instance": "vault",
                                 "app.kubernetes.io/name": "vault",
                                 "component": "server"
                              }
                           },
                           "topologyKey": "kubernetes.io/hostname"
                        },
                        "weight": 100
                     }
                  ]
               }
            },
            "annotations": {
               "vault.hashicorp.com/agent-configmap": "vault-agent-autounseal",
               "vault.hashicorp.com/agent-inject": "true",
               "vault.hashicorp.com/agent-pre-populate-only": "true",
               "vault.hashicorp.com/role": "vault"
            },
            "auditStorage": {
               "enabled": true,
               "size": "1Gi",
               "storageClass": "longhorn-single"
            },
            "dataStorage": {
               "size": "2Gi",
               "storageClass": "longhorn-single"
            },
            "extraArgs": "-config=/vault/secrets/server-config",
            "extraLabels": {
               "unseal-injector": "enabled"
            },
            "ha": {
               "enabled": true,
               "raft": {
                  "config": "",
                  "enabled": true
               },
               "replicas": 3
            },
            "volumeMounts": [
               {
                  "mountPath": "/vault-tls-internal",
                  "name": "vault-tls-internal"
               },
               {
                  "mountPath": "/vault-tls-web",
                  "name": "vault-tls-web"
               }
            ],
            "volumes": [
               {
                  "name": "vault-tls-internal",
                  "secret": {
                     "secretName": "vault-internal-tls-secret"
                  }
               },
               {
                  "name": "vault-tls-web",
                  "secret": {
                     "secretName": "wildcard-tls-secret"
                  }
               }
            ]
         },
         "ui": {
            "activeVaultPodOnly": true,
            "enabled": true,
            "externalPort": 443,
            "loadBalancerIP": "192.168.80.3",
            "serviceType": "LoadBalancer",
            "targetPort": 8300
         }
      }
   }
}
...
