apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wirywolf-crds
  namespace: argocd
spec:
  project: wirywolf
  source:
    repoURL: 'https://github.com/ameyp/k3s-cluster'
    targetRevision: 'main'
    path: root/crds
    directory:
      jsonnet:
        extVars:
          - name: mode
            value: 'test'
        libs:
          - vendor
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

