{
   "apiVersion": "v1",
   "data": { },
   "kind": "Secret",
   "metadata": {
      "name": "postgresql-initial-password",
      "namespace": "databases"
   },
   "stringData": {
      "postgres-password": "postgrespassword"
   },
   "type": "Opaque"
}
