---
{
   "apiVersion": "source.toolkit.fluxcd.io/v1beta2",
   "kind": "HelmRepository",
   "metadata": {
      "name": "traefik",
      "namespace": "flux-system"
   },
   "spec": {
      "interval": "24h",
      "url": "https://helm.traefik.io/traefik"
   }
}
---
{
   "apiVersion": "helm.toolkit.fluxcd.io/v2beta1",
   "kind": "HelmRelease",
   "metadata": {
      "name": "traefik",
      "namespace": "flux-system"
   },
   "spec": {
      "chart": {
         "spec": {
            "chart": "traefik",
            "interval": "12h",
            "sourceRef": {
               "kind": "HelmRepository",
               "name": "traefik",
               "namespace": "flux-system"
            },
            "version": "20.8.0"
         }
      },
      "dependsOn": [
         {
            "name": "metallb"
         }
      ],
      "install": {
         "createNamespace": true
      },
      "interval": "30m",
      "releaseName": "traefik",
      "targetNamespace": "traefik",
      "values": {
         "podAnnotations": {
            "prometheus.io/port": 8082,
            "prometheus.io/scrape": true
         },
         "ports": {
            "web": {
               "redirectTo": "websecure"
            },
            "websecure": {
               "tls": {
                  "enabled": true
               }
            }
         },
         "priorityClassName": "system-cluster-critical",
         "providers": {
            "kubernetesIngress": {
               "publishedService": {
                  "enabled": true
               }
            }
         },
         "rbac": {
            "enabled": true
         },
         "service": {
            "ipFamilyPolicy": "PreferDualStack",
            "spec": {
               "loadBalancerIP": "192.168.80.10"
            }
         },
         "tolerations": [
            {
               "key": "CriticalAddonsOnly",
               "operator": "Exists"
            },
            {
               "effect": "NoSchedule",
               "key": "node-role.kubernetes.io/control-plane",
               "operator": "Exists"
            },
            {
               "effect": "NoSchedule",
               "key": "node-role.kubernetes.io/master",
               "operator": "Exists"
            }
         ]
      }
   }
}
...
