global:
  tlsDisable: false
ui:
  enabled: true
  activeVaultPodOnly: true
  externalPort: %(webPort)d
  targetPort: %(webPort)d
server:
  extraArgs: "-config=/vault/secrets/server-config"
  logLevel: trace
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-pre-populate-only: 'true' # No sidecar
    vault.hashicorp.com/role: 'vault'
    vault.hashicorp.com/agent-configmap: 'vault-agent-autounseal'
  ha:
    enabled: true
    replicas: %(replicas)d
    raft:
      enabled: true
      config: ""
  dataStorage:
    size: 2Gi
    storageClass: local-path
  auditStorage:
    enabled: true
    size: 1Gi
    storageClass: local-path
  volumes:
    - name: "vault-tls"
      secret:
        secretName: %(tlsSecret)s
    - name: "vault-tls-web"
      secret:
        secretName: %(webSecret)s
  volumeMounts:
    - mountPath: "/vault-tls"
      name: "vault-tls"
    - mountPath: "/vault-tls-web"
      name: "vault-tls-web"
  extraEnvironmentVars:
    VAULT_CACERT: "/vault-tls/tls.crt"
  extraLabels:
    unseal-injector: enabled
  affinity: |
    # Identical to the default, minus app.kubernetes.io/name, because that seems to be the chart name.
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/instance: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname
injector:
  enabled: true
  webhook:
    objectSelector:
      matchLabels:
        vault-injector: enabled
