global:
  tlsDisable: false
ui:
  enabled: true
  activeVaultPodOnly: true
  externalPort: %(webPort)d
  targetPort: %(webPort)d
server:
  extraArgs: "-config=/vault/secrets/server-config"
  logLevel: trace
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-pre-populate-only: 'true' # No sidecar
    vault.hashicorp.com/role: 'vault'
    vault.hashicorp.com/agent-configmap: 'vault-agent-autounseal'
  ha:
    enabled: true
    replicas: 1
    raft:
      enabled: true
      config: ""
  dataStorage:
    size: 2Gi
    storageClass: longhorn
  auditStorage:
    enabled: true
    size: 1Gi
    storageClass: longhorn
  volumes:
    - name: "vault-tls"
      secret:
        secretName: %(tlsSecret)s
    - name: "vault-tls-web"
      secret:
        secretName: %(webSecret)s
  volumeMounts:
    - mountPath: "/vault-tls"
      name: "vault-tls"
    - mountPath: "/vault-tls-web"
      name: "vault-tls-web"
  extraEnvironmentVars:
    VAULT_CACERT: "/vault-tls/tls.crt"
  extraLabels:
    unseal-injector: enabled
  # Changed from required to preferred because for some reason even a single pod fails to deploy on my test cluster.
  # And since I've changed this, might as well deploy all 3 even on my test cluster.
  affinity: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: vault
                app.kubernetes.io/instance: vault
                component: server
            topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 0.125
injector:
  enabled: true
  webhook:
    objectSelector:
      matchLabels:
        vault-injector: enabled
  resources:
    requests:
      cpu: 0.125
