{
   "apiVersion": "redhatcop.redhat.io/v1alpha1",
   "kind": "DatabaseSecretEngineStaticRole",
   "metadata": {
      "name": "immich",
      "namespace": "vault"
   },
   "spec": {
      "authentication": {
         "path": "kubernetes",
         "role": "operator"
      },
      "credentialType": "password",
      "dBName": "immich",
      "passwordCredentialConfig": { },
      "path": "databases/postgresql",
      "rotationPeriod": 86400,
      "rotationStatements": [
         "ALTER USER \"{{name}}\" WITH PASSWORD '{{password}}';"
      ],
      "username": "immich"
   }
}
